/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

/**
 *
 * @author dinesh
 */
public class PowerFlowCascadeGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form PowerFlowCascadeGUI2
     */
    public PowerFlowCascadeGUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        preferencesMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        createNetworkMenuItem = new javax.swing.JMenuItem();
        editNetworkMenuItem = new javax.swing.JMenuItem();
        editEventsMenuItem = new javax.swing.JMenuItem();
        editSfinaParametersMenuItem = new javax.swing.JMenuItem();
        editBackendParametersMenuItem = new javax.swing.JMenuItem();
        experimentMenu = new javax.swing.JMenu();
        runMenuItem = new javax.swing.JMenuItem();
        stopMenuItem = new javax.swing.JMenuItem();
        configurationsMenuItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        showAnalyticsMenuItem = new javax.swing.JMenuItem();
        showLogMenuItem = new javax.swing.JMenuItem();
        showExperimentExplorerMenuItem = new javax.swing.JMenuItem();
        showNetworkMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        preferencesMenuItem.setText("Preferences");
        preferencesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(preferencesMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        createNetworkMenuItem.setText("Create Network");
        createNetworkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNetworkMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(createNetworkMenuItem);

        editNetworkMenuItem.setText("Edit Network");
        editMenu.add(editNetworkMenuItem);

        editEventsMenuItem.setText("Edit Events");
        editEventsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventsMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(editEventsMenuItem);

        editSfinaParametersMenuItem.setText("Edit Sfina Parameters");
        editSfinaParametersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSfinaParametersMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(editSfinaParametersMenuItem);

        editBackendParametersMenuItem.setText("Edit Backend Parameters");
        editMenu.add(editBackendParametersMenuItem);

        menuBar.add(editMenu);

        experimentMenu.setText("Experiment");

        runMenuItem.setText("Run");
        experimentMenu.add(runMenuItem);

        stopMenuItem.setText("Stop");
        experimentMenu.add(stopMenuItem);

        configurationsMenuItem.setText("Configurations");
        configurationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationsMenuItemActionPerformed(evt);
            }
        });
        experimentMenu.add(configurationsMenuItem);

        menuBar.add(experimentMenu);

        windowMenu.setText("Window");

        showAnalyticsMenuItem.setText("Analytics");
        showAnalyticsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAnalyticsMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showAnalyticsMenuItem);

        showLogMenuItem.setText("Logs");
        showLogMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLogMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showLogMenuItem);

        showExperimentExplorerMenuItem.setText("Experiments");
        showExperimentExplorerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showExperimentExplorerMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showExperimentExplorerMenuItem);

        showNetworkMenuItem.setText("Network");
        showNetworkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNetworkMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showNetworkMenuItem);

        menuBar.add(windowMenu);

        helpMenu.setText("Help");

        helpMenuItem.setText("Help");
        helpMenu.add(helpMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferencesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferencesMenuItemActionPerformed

    private void createNetworkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNetworkMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNetworkMenuItemActionPerformed

    private void editEventsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEventsMenuItemActionPerformed

    private void editSfinaParametersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSfinaParametersMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSfinaParametersMenuItemActionPerformed

    private void showAnalyticsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAnalyticsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAnalyticsMenuItemActionPerformed

    private void showLogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLogMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showLogMenuItemActionPerformed

    private void showExperimentExplorerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showExperimentExplorerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showExperimentExplorerMenuItemActionPerformed

    private void showNetworkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNetworkMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showNetworkMenuItemActionPerformed

    private void configurationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configurationsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerFlowCascadeGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem configurationsMenuItem;
    private javax.swing.JMenuItem createNetworkMenuItem;
    private javax.swing.JMenuItem editBackendParametersMenuItem;
    private javax.swing.JMenuItem editEventsMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editNetworkMenuItem;
    private javax.swing.JMenuItem editSfinaParametersMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu experimentMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JMenuItem runMenuItem;
    private javax.swing.JMenuItem showAnalyticsMenuItem;
    private javax.swing.JMenuItem showExperimentExplorerMenuItem;
    private javax.swing.JMenuItem showLogMenuItem;
    private javax.swing.JMenuItem showNetworkMenuItem;
    private javax.swing.JMenuItem stopMenuItem;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables
}
