/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

import actions.editMenu.CreateNetworkMenuItemAction;
import actions.editMenu.EditBackendParametersMenuItemAction;
import actions.editMenu.EditEventsMenuItemAction;
import actions.editMenu.EditNetworkMenuItemAction;
import actions.editMenu.EditSfinaParametersMenuItemAction;
import actions.fileMenu.ExitMenuItemAction;
import actions.helpMenu.AboutMenuItemAction;
import actions.helpMenu.HelpMenuItemAction;
import actions.runMenu.CancelMenuItemAction;
import actions.runMenu.ConfigurationsMenuItemAction;
import actions.runMenu.RunMenuItemAction;
import actions.windowMenu.ShowAnalyticsMenuItemAction;
import actions.windowMenu.ShowExperimentExplorerMenuItemAction;
import actions.windowMenu.ShowLogMenuItemAction;

/**
 *
 * @author dinesh
 */
public class PowerFlowCascadeGUI3 extends javax.swing.JFrame {

    /**
     * Creates new form PowerFlowCascadeGUI2
     */
    public PowerFlowCascadeGUI3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        
        menuBar = new javax.swing.JMenuBar();
        
        fileMenu = new javax.swing.JMenu("File");
        preferencesMenuItem = new javax.swing.JMenuItem("Preferences");
        exitMenuItem = new javax.swing.JMenuItem("Exit");
        editMenu = new javax.swing.JMenu("Edit");
        createNetworkMenuItem = new javax.swing.JMenuItem("Create Network");
        editNetworkMenuItem = new javax.swing.JMenuItem("Edit Network");
        editEventsMenuItem = new javax.swing.JMenuItem("Edit Events");
        editSfinaParametersMenuItem = new javax.swing.JMenuItem("Edit Sfina Parameters");
        editBackendParametersMenuItem = new javax.swing.JMenuItem("Edit Backend Parameters");
        experimentMenu = new javax.swing.JMenu("Experiment");
        runMenuItem = new javax.swing.JMenuItem("Run");
        cancelMenuItem = new javax.swing.JMenuItem("Stop");
        configurationsMenuItem = new javax.swing.JMenuItem("Configurations");
        windowMenu = new javax.swing.JMenu("Window");
        showAnalyticsMenuItem = new javax.swing.JMenuItem("Analytics");
        showLogMenuItem = new javax.swing.JMenuItem("Log");
        showExperimentExplorerMenuItem = new javax.swing.JMenuItem("Experiment Explorer");
        showNetworkMenuItem = new javax.swing.JMenuItem("Network");
        helpMenu = new javax.swing.JMenu("Help");
        helpMenuItem = new javax.swing.JMenuItem("Help");
        aboutMenuItem = new javax.swing.JMenuItem("About");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        // Add Action Listeners
        // File Menu
        exitMenuItem.addActionListener(new ExitMenuItemAction(this));
        
        // Edit Menu
        createNetworkMenuItem.addActionListener(new CreateNetworkMenuItemAction(this));
        editNetworkMenuItem.addActionListener(new EditNetworkMenuItemAction(this));
        editBackendParametersMenuItem.addActionListener(new EditBackendParametersMenuItemAction(this));
        editEventsMenuItem.addActionListener(new EditEventsMenuItemAction(this));
        editSfinaParametersMenuItem.addActionListener(new EditSfinaParametersMenuItemAction(this));

       // Experiment Menu Items
        runMenuItem.addActionListener(new RunMenuItemAction(this));
        cancelMenuItem.addActionListener(new CancelMenuItemAction(this));
        configurationsMenuItem.addActionListener(new ConfigurationsMenuItemAction(this));

       // Window Menu Items
        showExperimentExplorerMenuItem.addActionListener(new ShowExperimentExplorerMenuItemAction(this));
        showAnalyticsMenuItem.addActionListener(new ShowAnalyticsMenuItemAction(this));
        showLogMenuItem.addActionListener(new ShowLogMenuItemAction(this));

       // About Menu Items
        helpMenuItem.addActionListener(new HelpMenuItemAction(this));
        aboutMenuItem.addActionListener(new AboutMenuItemAction(this));

        fileMenu.add(preferencesMenuItem);
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);

        editMenu.add(createNetworkMenuItem);
        editMenu.add(editNetworkMenuItem);
        editMenu.add(editEventsMenuItem);
        editMenu.add(editSfinaParametersMenuItem);
        editMenu.add(editBackendParametersMenuItem);
        menuBar.add(editMenu);

        experimentMenu.add(runMenuItem);
        experimentMenu.add(cancelMenuItem);
        experimentMenu.add(configurationsMenuItem);
        menuBar.add(experimentMenu);

        windowMenu.add(showAnalyticsMenuItem);
        windowMenu.add(showLogMenuItem);
        windowMenu.add(showExperimentExplorerMenuItem);
        windowMenu.add(showNetworkMenuItem);
        menuBar.add(windowMenu);

        helpMenu.add(helpMenuItem);
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }

    public javax.swing.JDesktopPane getDesktop(){
        return desktop;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerFlowCascadeGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerFlowCascadeGUI3().setVisible(true);
            }
        });
    }

    // variables                 
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem configurationsMenuItem;
    private javax.swing.JMenuItem createNetworkMenuItem;
    private javax.swing.JMenuItem editBackendParametersMenuItem;
    private javax.swing.JMenuItem editEventsMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editNetworkMenuItem;
    private javax.swing.JMenuItem editSfinaParametersMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu experimentMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JMenuItem runMenuItem;
    private javax.swing.JMenuItem showAnalyticsMenuItem;
    private javax.swing.JMenuItem showExperimentExplorerMenuItem;
    private javax.swing.JMenuItem showLogMenuItem;
    private javax.swing.JMenuItem showNetworkMenuItem;
    private javax.swing.JMenuItem cancelMenuItem;
    private javax.swing.JMenu windowMenu;

}
